name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run make4ht
      # uses: michal-h21/make4ht-action@master
      uses: docker://hub.docker.com/michalh21/make4ht-docker:latest
      env:
        command: "make; make4ht -uslm final -a debug -c config -d out -f html5+common_domfilters -e build.mk4  tex4ht-doc.tex"
    - name: Publish the web pages
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./out
